# -*- coding: utf-8 -*-
"""lingplotter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11eDD7Pz6PWUwSk7m9sL94sE0UleB3XLC
"""

import pandas as pd
import seaborn as sns
from matplotlib.pyplot import savefig



time2analyze = pd.DataFrame({"Size of Corpus (kilobytes)":[9.4,80.7,2930]*2, 
                             "Analyser":["Python"]*3+["HFST"]*3, 
                             "Time to Analyse (seconds)":[0.2,1.3,22.5,0.33,
                                                          0.32,1.58]})
sns.catplot(x='Size of Corpus (kilobytes)', y='Time to Analyse (seconds)', 
            hue='Analyser', data=time2analyze, kind='bar', 
            palette = ["tomato","indigo"])
savefig('time2analyze',transparent = True,format='eps')
memrequired = pd.DataFrame({"Size of Corpus (kilobytes)":[9.4,80.7,2930]*2, 
                            "Analyser":["Python"]*3+["HFST"]*3, 
                            "Memory Required (megabytes)":[58.9,59.4,217.9,
                                                           12.9,13.3,13.1]})
sns.catplot(x='Size of Corpus (kilobytes)', y='Memory Required (megabytes)', 
            hue='Analyser', data=memrequired, kind='bar', 
            palette = ["tomato","indigo"])
savefig('memreq',transparent = True,format='eps')

